name: Build & Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        steps:
            - name: Create AWS Credentials file
              run: |
                  mkdir -p ~/.aws
                  echo "[portfolio-3]" > ~/.aws/credentials
                  echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
                  echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
            - name: Clone Repository
              uses: actions/checkout@v3
            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Install Dependencies
              run: bun i
            - name: Building & Deploy Project
              run: |
                  bunx sst deploy --stage=production
